version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "7068:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AlejandroPonnosUn10(!)
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend
    restart: unless-stopped

  api:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    container_name: dotnet_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8607:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SistemaPedidosDB;User=sa;Password=AlejandroPonnosUn10(!);TrustServerCertificate=True;
      - APP_NAME=Sistema de Gestión - More Than Brows
    depends_on:
      - sqlserver
    volumes:
      - ./api:/app
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data: