services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "7068:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=AlejandroPonnosUn10(!)
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=2048
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend
    restart: unless-stopped

  db-init:
    image: mcr.microsoft.com/mssql-tools
    container_name: db-init
    depends_on:
      - sqlserver
    volumes:
      - ./createDbSqlServer.sql:/createDbSqlServer.sql
    networks:
      - backend
    command: >
      bash -c "
      echo ' Esperando a que SQL Server esté listo...' &&
      sleep 35 &&
      echo ' Ejecutando script de inicialización...' &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'AlejandroPonnosUn10(!)' -i /createDbSqlServer.sql &&
      echo ' Base de datos inicializada correctamente' &&
      echo ' Verificando tablas creadas:' &&
      /opt/mssql-tools/bin/sqlcmd -S sqlserver -U sa -P 'AlejandroPonnosUn10(!)' -d SistemaPedidosDB -Q 'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES ORDER BY TABLE_NAME'
      "
    restart: "no"

  api:
    image: gsvmm/reto-desarrollo-api:latest
    container_name: dotnet_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8607:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__SistemaPedidosDB=Server=sqlserver,1433;Database=SistemaPedidosDB;User Id=sa;Password=AlejandroPonnosUn10(!);TrustServerCertificate=True;
      - APP_NAME=Sistema de Gestión - More Than Brows
    depends_on:
      - sqlserver
      - db-init
    networks:
      - backend
    restart: unless-stopped

networks:
  backend:
    driver: bridge

volumes:
  sqlserver_data: